/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrojkeRouteImport } from './routes/brojke'
import { Route as KartaRouteImport } from './routes/karta'
import { Route as OProjektuRouteImport } from './routes/o-projektu'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UdrugeRouteImport } from './routes/udruge'
import { Route as UdrugaSlugRouteImport } from './routes/udruga.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrojkeRoute = BrojkeRouteImport.update({
  id: '/brojke',
  path: '/brojke',
  getParentRoute: () => rootRouteImport,
} as any)
const KartaRoute = KartaRouteImport.update({
  id: '/karta',
  path: '/karta',
  getParentRoute: () => rootRouteImport,
} as any)
const OProjektuRoute = OProjektuRouteImport.update({
  id: '/o-projektu',
  path: '/o-projektu',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UdrugeRoute = UdrugeRouteImport.update({
  id: '/udruge',
  path: '/udruge',
  getParentRoute: () => rootRouteImport,
} as any)
const UdrugaSlugRoute = UdrugaSlugRouteImport.update({
  id: '/udruga/$slug',
  path: '/udruga/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brojke': typeof BrojkeRoute
  '/karta': typeof KartaRoute
  '/o-projektu': typeof OProjektuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/udruge': typeof UdrugeRoute
  '/udruga/$slug': typeof UdrugaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brojke': typeof BrojkeRoute
  '/karta': typeof KartaRoute
  '/o-projektu': typeof OProjektuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/udruge': typeof UdrugeRoute
  '/udruga/$slug': typeof UdrugaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brojke': typeof BrojkeRoute
  '/karta': typeof KartaRoute
  '/o-projektu': typeof OProjektuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/udruge': typeof UdrugeRoute
  '/udruga/$slug': typeof UdrugaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brojke'
    | '/karta'
    | '/o-projektu'
    | '/sitemap.xml'
    | '/udruge'
    | '/udruga/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brojke'
    | '/karta'
    | '/o-projektu'
    | '/sitemap.xml'
    | '/udruge'
    | '/udruga/$slug'
  id:
    | '__root__'
    | '/'
    | '/brojke'
    | '/karta'
    | '/o-projektu'
    | '/sitemap.xml'
    | '/udruge'
    | '/udruga/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrojkeRoute: typeof BrojkeRoute
  KartaRoute: typeof KartaRoute
  OProjektuRoute: typeof OProjektuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UdrugeRoute: typeof UdrugeRoute
  UdrugaSlugRoute: typeof UdrugaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brojke': {
      id: '/brojke'
      path: '/brojke'
      fullPath: '/brojke'
      preLoaderRoute: typeof BrojkeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karta': {
      id: '/karta'
      path: '/karta'
      fullPath: '/karta'
      preLoaderRoute: typeof KartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-projektu': {
      id: '/o-projektu'
      path: '/o-projektu'
      fullPath: '/o-projektu'
      preLoaderRoute: typeof OProjektuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/udruge': {
      id: '/udruge'
      path: '/udruge'
      fullPath: '/udruge'
      preLoaderRoute: typeof UdrugeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/udruga/$slug': {
      id: '/udruga/$slug'
      path: '/udruga/$slug'
      fullPath: '/udruga/$slug'
      preLoaderRoute: typeof UdrugaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrojkeRoute: BrojkeRoute,
  KartaRoute: KartaRoute,
  OProjektuRoute: OProjektuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UdrugeRoute: UdrugeRoute,
  UdrugaSlugRoute: UdrugaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
